function TreatmentPlan = newTreatmentPlan

TreatmentPlan = struct('SpotNum',           [],...
                       'SpotPosX',          [],...
                       'SpotPosY',          [],...
                       'SpotPosZ',          [],...
                       'SonicationTime',    [],...
                       'SonicationPeriod',  [],...
                       'DutyCycle',         [],...
                       'CoolingTime',       []);