function key = getKey

key = struct('SpotNum',            'SpotNum',...
             'SpotPosX',           'SpotPosX',...
             'SpotPosY',           'SpotPosY',...
             'SpotPosZ',           'SpotPosZ',...
             'SonicationTime',     'SonicationTime',...
             'SonicationPeriod',   'SonicationPeriod',...
             'DutyCycle',          'DutyCycle',...
             'CoolingTime',        'CoolingTime');